# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteoptions',
            name='domain',
            field=models.CharField(db_index=True, default='cube-drone.com', max_length=100),
        ),
        migrations.AddField(
            model_name='siteoptions',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
