# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_siteoptions_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterIntegration',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.SiteOptions')),
                ('username', models.CharField(default='classam', max_length=50)),
                ('widget_id', models.CharField(default='304715092187025408', max_length=50)),
                ('consumer_key', models.CharField(default='', help_text='Get from apps.twitter.com', max_length=100)),
                ('consumer_secret', models.CharField(default='', help_text='Get from apps.twitter.com', max_length=100)),
                ('access_key', models.CharField(default='', help_text='Get from apps.twitter.com', max_length=100)),
                ('access_secret', models.CharField(default='', help_text='Get from apps.twitter.com', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='siteoptions',
            name='twitter_access_key',
        ),
        migrations.RemoveField(
            model_name='siteoptions',
            name='twitter_access_secret',
        ),
        migrations.RemoveField(
            model_name='siteoptions',
            name='twitter_consumer_key',
        ),
        migrations.RemoveField(
            model_name='siteoptions',
            name='twitter_consumer_secret',
        ),
        migrations.RemoveField(
            model_name='siteoptions',
            name='twitter_username',
        ),
        migrations.RemoveField(
            model_name='siteoptions',
            name='twitter_widget_id',
        ),
    ]
