# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 02:16
from __future__ import unicode_literals

import autoslug.fields
import dashboard.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20160310_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteoptions',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=dashboard.models.slugify, unique=True),
        ),
    ]
