# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 20:45
from __future__ import unicode_literals

import autoslug.fields
import comics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(help_text='The title of the blog post', max_length=100), slugify=comics.models.slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=comics.models.title, slugify=comics.models.slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(help_text='The title of the image', max_length=100), slugify=comics.models.slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(help_text='The title of the video', max_length=100), slugify=comics.models.slugify, unique=True),
        ),
    ]
