# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 08:57
from __future__ import unicode_literals

import autoslug.fields
import comics.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_comic_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=comics.models.slugify, unique=True),
        ),
    ]
