# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 19:08
from __future__ import unicode_literals

import autoslug.fields
import comics.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_auto_20160220_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=comics.models.slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=comics.models.slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=comics.models.slugify, unique=True),
        ),
    ]
