import string
import random
try:
    from slugify import slugify
except ImportError:
    def slugify(words):
        return words.lower().replace(" ", "-")

titles = [
    'captain',
    'lieutenant',
    'leftenant',
    'colonel',
    'general',
    'major',
    'sir',
    'sensei',
    'lord',
    'duke',
    'president',
    'master',
    'mister',
    'miss',
    'lady',
    'queen',
    'king',
    'doctor',
    'monsieur',
    'madame',
    'senor',
    'senorita',
    'lord commander',
    'luchadore',
    'commodore',
    'emperor',
    'super-emperor',
    'madam',
    'dame',
    'professor',
    'father',
    'brother',
    'sister',
    'reverend',
]

adjectives = [
    'heroic',
    'magnificent',
    'mighty',
    'amazing',
    'wonderful',
    'fantastic',
    'incredible',
    'spectacular',
    'tremendous',
    'throbbing',
    'enormous',
    'terrific',
    'wondrous',
    'spectacular',
    'big',
    'tiny',
    'small',
    'mighty',
    'musky',
    'transparent',
    'opaque',
    'light',
    'dark',
    'scary',
    'extraneous',
    'huge',
    'aqua',
    'aquamarine',
    'azure',
    'beige',
    'black',
    'almond',
    'blue',
    'brown',
    'chartreuse',
    'coral',
    'cornflower',
    'crimson',
    'cyan',
    'navy',
    'goldenrod',
    'gray',
    'grey',
    'green',
    'khaki',
    'magenta',
    'olive',
    'salmon',
    'slate',
    'turquoise',
    'violet',
    'pink',
    'skyblue',
    'brick',
    'white',
    'fuchsia',
    'gainsboro',
    'golden',
    'honeydew',
    'hotpink',
    'indigo',
    'ivory',
    'lavender',
    'lemon',
    'chiffon',
    'purple',
    'orchid',
    'linen',
    'rose',
    'orange',
    'pale',
    'sandy',
    'seashell',
    'silver',
    'tan',
    'teal',
    'thistle',
    'violet',
    'plaid',
    'polkadot',
    'paisley',
    'iron',
    'bronze',
    'stone',
    'birch',
    'cedar',
    'cherrywood',
    'sandalwood',
    'pine',
    'fir',
    'yew',
    'hemlock',
    'spruce',
    'chestnut',
    'boxwood',
    'butternut',
    'camphor',
    'elm',
    'oak',
    'mahogany',
    'huckleberry',
    'ironwood',
    'maple',
    'poplar',
    'unpoplar',
    'teak',
    'beech',
    'nutmeg',
    'willow',
    'cinnamon',
    'allspice',
    'basil',
    'cardamom',
    'clove',
    'garlic',
    'juniper',
    'gin-soaked',
    'rum',
    'lime',
    'licorice',
    'capable',
    'trustworthy',
    'heavy',
    'fast',
    'slow',
    'charming',
    'noticeable',
    'sly',
    'slippery',
    'sluggish',
    'casual',
    'cautious',
    'cement',
    'diabolical',
    'evil',
    'metropolitan',
    'banana',
    'good',
    'neutral',
    'apple',
    'pear',
    'winter',
    'spring',
    'fall',
    'autumn',
    'summer',
    'garbage',
    'imposing',
    'correct',
    'underhanded',
    'salty',
    'coffee',
    'cheese',
    'floppy',
    'unpopular',
    'popular',
    'forgettable',
    'misty',
    'soulful',
    'gassy',
    'spectacular',
    'sleepy',
    'laudable',
    'comfortable',
    'soft',
    'dicey',
    'memorable',
    'patterned',
    'greasy',
    'elongated',
    'long',
    'collapsible',
    'mysterious',
    'expandible',
    'delicious',
    'edible',
    'scattered',
    'impenetrable',
    'sexy',
    'curvaceous',
    'intractable',
    'unavoidable',
    'impressive',
    'impeccable',
    'fussy',
    'touchable',
    'intermittent',
    'scandalous',
    'murky',
    'sloshing',
    'damp',
]

nouns = [
    'apparatus',
    'britches',
    'mystery',
    'secret',
    'butt',
    'hunter',
    'fisher',
    'bean',
    'harvest',
    'mixer',
    'hand',
    'finger',
    'nose',
    'eye',
    'belly',
    'jeans',
    'plan',
    'disk',
    'horse',
    'battery',
    'staple',
    'face',
    'button',
    'byte',
    'cabinet',
    'vehicle',
    'canyon',
    'dance',
    'crayon',
    'sausage',
    'meat',
    'napkin',
    'device',
    'cape',
    'chair',
    'person',
    'character',
    'burger',
    'ham',
    'beef',
    'book',
    'circuit',
    'civilian',
    'clamp',
    'circuitry',
    'calculus',
    'cloud',
    'code',
    'coast',
    'coin',
    'corporation',
    'concern',
    'space',
    'key',
    'object',
    'heart',
    'stapler',
    'mug',
    'bottle',
    'cable',
    'note',
    'lamp',
    'shelf',
    'blanket',
    'dong',
    'board',
    'indicator',
    'injection',
    'investment',
    'issue',
    'job',
    'knife',
    'thing',
    'phone',
    'sweater',
    'pants',
    'boot',
    'sock',
    'socks',
    'hat',
    'ring',
    'dong',
    'wrap',
    'holder',
    'pen',
    'pencil',
    'bag',
    'dispenser',
    'butter',
    'potato',
    'sword',
    'shield',
    'spear',
    'staff',
    'shaft',
    'slab',
    'sandwich',
    'song',
    'glaive',
    'axe',
    'crossbow',
    'armour',
    'lamp',
    'club',
    'cage'
]

firstnames = [
    'carl',
    'carla',
    'tim',
    'mary',
    'peter',
    'kimmy',
    'steve',
    'jennifer',
    'frank',
    'youssef',
    'pierre',
    'george',
    'aya',
    'thiago',
    'daniel',
    'liam',
    'jack',
    'agustin',
    'santiago',
    'noah',
    'sofia',
    'olivia',
    'madison',
    'chloe',
    'camilla',
    'hiroto',
    'rasmus',
    'charlie',
    'miguel',
    'alexander',
    'emma',
    'maya',
    'sara',
    'amelia',
    'tiffany',
    'arnold',
    'ronald',
    'hogan',
    'doug',
    'pete',
    'jim',
    'james',
]



def title():
    return random.choice(titles)


def adjective():
    return random.choice(adjectives)


def noun():
    return random.choice(nouns)


def firstname():
    return random.choice(firstnames)


def name():
    return slugify(proper_name())


def thing():
    return adjective()+" "+noun()


def proper_name():
    slab = random.choice([
        noun(),
        adjective(),
        noun()+noun(),
        noun()+adjective(),
        adjective()+noun()])
    if random.choice([True, False]):
        slab = firstname() + " " + slab
    if random.choice([True, False]):
        slab = title() + " " + slab
    if len(slab.split(" ")) == 1:
        slab = proper_name() + " " + slab

    return slab.title()

def special_thing():
    return random.choice([
        "{}'s {}".format(proper_name(), noun().title()),
        "{}'s {}".format(proper_name(), thing().title()),
        "The {} of {}".format(thing().title(), proper_name()),
        "The {} {} {} of {}".format(adjective().title(), adjective().title(), noun().title(), proper_name()),
        ])

def markdown():
    words = ""
    for i in range(0, 10):
        if random.choice([True, False, False, False, False]):
            words = words + "#### "
        words = words + proper_name() + " "
        for i in range(0, random.randrange(3,30,1)):
            word = random.choice([noun(), adjective()])
            if random.choice([True, False, False]):
                word = "**{}**".format(word)
            elif random.choice([True, False, False]):
                word = "_{}_".format(word)
            words = words + word + " "
        words = words + ".\n\n"
    return words
