import string 
import random

titles = [
    'captain', 
    'lieutenant',
    'leftenant',
    'colonel',
    'general',
    'major',
    'sir',
    'sensei',
    'lord',
    'duke',
    'president',
    'master',
    'mister',
    'miss',
    'lady',
    'queen',
    'king',
    'doctor',
    'monsieur',
    'madame',
    'senor',
    'senorita',
]

adjectives = [
    'heroic',
    'magnificent',
    'mighty',
    'amazing',
    'wonderful',
    'fantastic',
    'incredible',
    'spectacular',
    'tremendous',
    'throbbing',
    'enormous',
    'terrific',
    'wondrous',
    'spectacular',
    'big',
    'tiny',
    'small',
    'mighty',
    'musky',
    'transparent',
    'opaque',
    'light',
    'dark',
    'scary',
    'extraneous',
    'huge',
    'aqua',
    'aquamarine',
    'azure',
    'beige',
    'black',
    'almond',
    'blue',
    'brown',
    'chartreuse',
    'coral',
    'cornflower',
    'crimson',
    'cyan',
    'navy',
    'goldenrod',
    'gray',
    'grey',
    'green',
    'khaki',
    'magenta',
    'olive',
    'salmon',
    'slate',
    'turquoise',
    'violet',
    'pink',
    'skyblue',
    'brick',
    'white',
    'fuchsia',
    'gainsboro',
    'golden',
    'honeydew',
    'hotpink',
    'indigo',
    'ivory',
    'lavender',
    'lemon',
    'chiffon',
    'purple',
    'orchid',
    'linen',
    'rose',
    'orange',
    'pale',
    'sandy',
    'seashell',
    'silver',
    'tan',
    'teal',
    'thistle',
    'violet',
    'plaid',
    'polkadot',
    'paisley',
    'iron',
    'bronze',
    'stone',
    'birch',
    'cedar',
    'cherrywood',
    'sandalwood',
    'pine',
    'fir',
    'yew',
    'hemlock',
    'spruce',
    'chestnut',
    'boxwood',
    'butternut',
    'camphor',
    'elm',
    'oak',
    'mahogany',
    'huckleberry',
    'ironwood',
    'maple',
    'poplar',
    'unpoplar',
    'teak',
    'beech',
    'nutmeg',
    'willow',
    'cinnamon',
    'allspice',
    'basil',
    'cardamom',
    'clove',
    'garlic',
    'juniper',
    'gin-soaked',
    'rum',
    'lime',
    'licorice',
    'capable',
    'trustworthy',
    'heavy',
    'fast',
    'slow',
    'charming',
    'noticeable',
    'sly',
    'slippery',
    'sluggish',
    'casual',
    'cautious',
    'cement',
    'diabolical',
    'evil',
    'metropolitan',
    'banana',
    'good',
    'neutral',
    'apple',
    'pear',
    'winter',
    'spring',
    'fall',
    'autumn',
    'summer',
    'garbage',
    'imposing',
    'correct',
    'underhanded',
    'salty',
    'coffee',
    'cheese',
    'floppy',
    'unpopular',
    'popular',
    'forgettable',
    'misty',
    'soulful',
    'gassy',
    'spectacular',
    'sleepy',
    'laudable',
    'comfortable',
    'soft',
    'dicey',
    'memorable',
    'patterned',
    'greasy',
    'elongated',
    'long',
    'collapsible',
    'mysterious',
    'expandible',
    'delicious',
    'edible',
    'scattered',
    'impenetrable',
    'sexy',
    'curvaceous',
    'intractable',
    'unavoidable',
    'impressive',
    'impeccable',
    'fussy'
]

nouns = [
    'apparatus',
    'britches',
    'mystery',
    'secret',
    'butt',
    'hunter',
    'fisher',
    'bean',
    'harvest',
    'mixer',
    'hand',
    'finger',
    'nose',
    'eye',
    'belly',
    'jeans',
    'plan',
    'disk',
    'horse',
    'battery',
    'staple',
    'face',
    'button',
    'byte',
    'cabinet',
    'vehicle',
    'canyon',
    'dance',
    'crayon',
    'sausage',
    'meat',
    'napkin',
    'device',
    'cape',
    'chair',
    'person',
    'character',
    'burger',
    'ham',
    'beef',
    'book',
    'circuit',
    'civilian',
    'clamp',
    'circuitry',
    'calculus',
    'cloud',
    'code',
    'coast',
    'coin',
    'corporation',
    'concern',
    'space',
    'key',
    'object',
    'heart',
    'stapler',
    'mug',
    'bottle',
    'cable',
    'note',
    'lamp',
    'shelf',
    'blanket',
    'dong',
    'captain',
    'board',
    'indicator',
    'injection',
    'investment',
    'issue',
    'job',
    'knife',
    'thing',
    'phone',
    'sweater',
    'pants',
    'boot',
    'sock',
    'socks',
    'hat',
    'ring',
    'dong',
    'wrap',
    'holder',
    'pen',
    'pencil',
    'bag',
    'dispenser',
    'butter',
    'potato'
]


def title():
    return random.choice(titles)


def adjective():
    return random.choice(adjectives)


def noun():
    return random.choice(nouns)


def name():
    fn = random.choice([
        lambda: title()+"-"+adjective(),
        lambda: title()+"-"+noun(),
        lambda: title()+"-"+noun()+noun(),
        lambda: title()+"-"+adjective()+noun()])
    return fn()


def thing():
    return adjective()+" "+noun()


def special_thing():
    return string.capwords("the %s of %s's %s" % (thing(), name(), thing()))
